version: '3.8'

services:
  db_postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: Qq123456
      POSTGRES_DB: walletdb
      POSTGERS_CONNECTION: Host=postgres;Port=5432;Database=walletdb;Username=artem;Password=Qq123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Qq123456
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  wallet.api:
    image: wallet.api
    container_name: WalletsService
    build:
      context: .
      dockerfile: Wallet.API/Dockerfile
    environment: 
      CONNECTION_STRING: Host=postgres;Port=5432;Database=walletdb;Username=artem;Password=Qq123456
    ports:
      - "8080:8080"

volumes:
  pgdata:
  pgadmin_data:
